	http:
	  port: 8080
	admin:
	  port: 9876
	  host: localhost
	apiEndpoints:
	  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/apiEndpoints
	serviceEndpoints:
	  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/serviceEndpoints
	policies:
	  - basic-auth
	  - cors
	  - expression
	  - key-auth
	  - log
	  - oauth2
	  - proxy
	  - rate-limit
	pipelines:
	  # see: https://www.express-gateway.io/docs/configuration/gateway.config.yml/pipelines
